name: Run Makefile

on:
  push:
    branches:
      - '**'

jobs:
  run-makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Run Makefile target 'check-examples'
        run: |
          make generate-examples

      - name: Run Makefile target 'check-examples'
        run: |
          make check-examples